### NumPy Basics:-
#### What is NumPy
##### => (1) A python library for numerical computing
##### => (2) Provides n-dimensional arrays (ndarray), faster than python LISTS
##### => (3) Used in data science, machine learning, engineering and scientific computing

In [4]:
# installing
!pip install numpy

In [6]:
#importing
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


#### 1-D Arrays
##### An array that has 0-D arrays  as its elements is called uni-dimensional or 1-D array.

In [13]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


#### 2 - D Arrays
##### An array that has 1-D arrays as its elements is called a 2-D array.
##### These ara often used to represent matrix or 2nd order tensors.

In [16]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### 3-D Arrays
##### An array that has 2-D arrays (matrices) as its elements is called 3-D Array.
##### These are often used t represent a 3rd order tensor.

In [19]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### Check Number of Dimensions ?
##### NumPy Arrays provides that ndim attribut that returns an integer that tells us 
##### how many dimensions the array have

In [22]:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#### Higher Dimensional Arrays
##### An array cam have any number of dimensions.
##### When the array is created, you can define the number of dimensions by using the ndim argument.

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


#### Numpy Array Indexing
##### Access Array Elements
###### Array indexing is the same as accessing an array elements.
###### you can access an array element by referring to its index number
###### The indexes in NumPy arrays start with 0, meaning that the first element has index 0, adn the second has index 1 etc

In [32]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])

1


In [34]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1])

2


In [36]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


#### Access 2-D Arrays
##### To access elements from 2-D arrays we can use comma separated integers representing the dimension adn the index of the element.
##### Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represent the clm

In [39]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st wor:',arr[0,1])

2nd element on 1st wor: 2


In [41]:
import numpy as np 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row:',arr[1,4])

5th element on 2nd row: 10


#### Access 3-D Arrays
##### To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [46]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


#### Negative Indexing 
##### Use negative indexing to access an array from the end.

In [49]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dim: ',arr[1,-1])

last element from 2nd dim:  10


#### Slicing Arrays
##### Slicing in python means taking elements from one given index to another given index.
##### We pass slice instead of index like this : [start:end]
##### We can aslo define the stepm like this: [start:end:step]
##### If we don't pass start its considerred 0
##### IF we don't pass end its considered length of array in that dimension
##### If we don't pass step its considered 1

In [54]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [58]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


#### Negative Slicing 
##### Use the minus operator to refer to an index from the end:

In [61]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


#### STEP 
##### Use the step value to determine the step of the slicing 

In [64]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


#### Slicing 2 - D Arrays

In [67]:
import numpy as np 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [71]:
import numpy as np 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


#### NumPy Data Types


In [74]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [76]:
import numpy as np
arr = np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [78]:
import numpy as np
arr = np.array([1,2,3,4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [80]:
import numpy as np 
arr = np.array([1,2,3,4],dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


##  Converting DataType on Existing Arrays

In [83]:
import numpy as np
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [85]:
import numpy as np
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [87]:
import numpy as np 
arr = np.array([1,0,3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


### The Difference Between Copy and View 
#### => The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
#### => The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
#### => The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [90]:
import numpy as np 
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [92]:
# view 
import numpy as np

arr = np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


## Make changes in the view

In [95]:
import numpy as np 

arr = np.array([1,2,3,4,5])
x=arr.view()
x[0]=31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


### Check if Array Owns its Data 

In [98]:
import numpy as np
arr = np.array([1,2,3,4,5])

x = arr.copy()
y= arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## NumPy Array Shape 

In [101]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

(2, 4)


In [105]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
