#### Uses of SciPy
#### Scientific & Technical Computing

#### Data Science & Machine Learning Preprocessing

#### Image and Signal Processing

#### Engineering simulations (ODEs, FFTs)

#### Mathematical operations beyond NumPy

### 1. scipy.integrate — Integration & ODE Solvers
### Use: Numerical integration and solving ordinary differential equations.

### Functions:

### quad() – Integrate a function.

### odeint() – Solve ODEs.

In [3]:
from scipy import integrate

result, error = integrate.quad(lambda x: x**2, 0, 3)
print("Integral:", result)  # Output: 9.0


Integral: 9.000000000000002


In [5]:
#### 2. scipy.optimize — Optimization & Root Finding
#### Use: Find minimum/maximum of functions or solve equations.

#### Functions:

#### minimize() – Minimize a scalar function.

#### root() – Find the roots of a function.

In [7]:
from scipy.optimize import minimize

f = lambda x: x**2 + 3*x + 2
res = minimize(f, x0=0)
print(res.x)  # Optimal value of x


[-1.50000001]


In [9]:
#### 3. scipy.linalg — Linear Algebra
####  Use: Advanced linear algebra operations (more features than NumPy).

#### Functions:

####  inv() – Inverse of a matrix.

####  det() – Determinant.

####  eig() – Eigenvalues and eigenvectors.

In [11]:
from scipy.linalg import inv
import numpy as np

A = np.array([[1, 2], [3, 4]])
print("Inverse:\n", inv(A))



Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [13]:
#### 4. scipy.interpolate — Interpolation
#### Use: Estimate intermediate values between data points.

#### Functions:

#### interp1d() – 1D interpolation.

#### griddata() – Multidimensional interpolation.

In [15]:
from scipy.interpolate import interp1d
import numpy as np

x = np.array([0, 1, 2])
y = np.array([0, 2, 4])
f = interp1d(x, y)
print(f(1.5))  # Output: 3.0


3.0


In [17]:
#### 5. scipy.fft — Fast Fourier Transform
#### Use: Signal processing and frequency domain analysis.

#### Functions:

#### fft() – Fast Fourier Transform.

#### ifft() – Inverse FFT.

#### Example:

In [19]:
from scipy.fft import fft
import numpy as np

x = np.array([0, 1, 0, -1])
y = fft(x)
print(y)


[0.-0.j 0.-2.j 0.-0.j 0.+2.j]


In [21]:
#### 6. scipy.stats — Statistics
#### Use: Perform statistical operations and probability distributions.

#### Functions:

#### mean(), std(), mode()

#### norm, binom, poisson distributions

In [23]:
from scipy import stats

data = [1, 2, 2, 3, 4]
print("Mode:", stats.mode(data))


Mode: ModeResult(mode=2, count=2)


In [25]:
#### 7. scipy.sparse — Sparse Matrices
#### Use: Handle memory-efficient sparse matrices.

#### Functions:

#### csr_matrix(), csc_matrix()

#### sparse.linalg.spsolve()

In [27]:
from scipy.sparse import csr_matrix
import numpy as np

mat = csr_matrix([[0, 0, 1], [1, 0, 0], [0, 0, 2]])
print(mat)


  (0, 2)	1
  (1, 0)	1
  (2, 2)	2


In [29]:
#### 8. scipy.ndimage — Image Processing
#### Use: Apply filters and transformations to multidimensional images.

#### Functions:

#### gaussian_filter()

#### rotate(), zoom()

In [31]:
from scipy.ndimage import gaussian_filter
import numpy as np

img = np.random.rand(5,5)
blurred = gaussian_filter(img, sigma=1)
print(blurred)


[[0.48364131 0.32669003 0.2507631  0.27077947 0.3280582 ]
 [0.46932645 0.35636068 0.30833965 0.29914985 0.29626086]
 [0.57154079 0.46297632 0.41311114 0.39631587 0.35781812]
 [0.64856069 0.50749569 0.39741908 0.37511826 0.34671108]
 [0.61362437 0.45130264 0.29804267 0.25485381 0.23062863]]
